// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtwrbEHlsSUxP2ABx_lDYDeQYpXeyU5mk',
    appId: '1:1098014362367:web:397ddf478e541598dd5aca',
    messagingSenderId: '1098014362367',
    projectId: 'game-arcade-7edc5',
    authDomain: 'game-arcade-7edc5.firebaseapp.com',
    storageBucket: 'game-arcade-7edc5.appspot.com',
    measurementId: 'G-CHTM4F605T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjoNgNBZ74MisiGG4WPKD_S6jW4Xfb48U',
    appId: '1:1098014362367:android:199e41d83ee6aff4dd5aca',
    messagingSenderId: '1098014362367',
    projectId: 'game-arcade-7edc5',
    storageBucket: 'game-arcade-7edc5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsLNFB-7NVVSYP_UxFaxoNwc236KVKVmA',
    appId: '1:1098014362367:ios:478e5caddd9e16d3dd5aca',
    messagingSenderId: '1098014362367',
    projectId: 'game-arcade-7edc5',
    storageBucket: 'game-arcade-7edc5.firebasestorage.app',
    iosBundleId: 'com.example.gameArcade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsLNFB-7NVVSYP_UxFaxoNwc236KVKVmA',
    appId: '1:1098014362367:ios:478e5caddd9e16d3dd5aca',
    messagingSenderId: '1098014362367',
    projectId: 'game-arcade-7edc5',
    storageBucket: 'game-arcade-7edc5.firebasestorage.app',
    iosBundleId: 'com.example.gameArcade',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtwrbEHlsSUxP2ABx_lDYDeQYpXeyU5mk',
    appId: '1:1098014362367:web:3968a223118fa75add5aca',
    messagingSenderId: '1098014362367',
    projectId: 'game-arcade-7edc5',
    authDomain: 'game-arcade-7edc5.firebaseapp.com',
    storageBucket: 'game-arcade-7edc5.firebasestorage.app',
    measurementId: 'G-MCM7245812',
  );
}
